# Generated by Django 3.0.6 on 2020-06-14 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('additional_info', models.CharField(blank=True, max_length=500, null=True)),
                ('img_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_title', models.CharField(blank=True, max_length=300, null=True)),
                ('type_1', models.CharField(blank=True, max_length=500, null=True)),
                ('price_1', models.IntegerField(blank=True, null=True)),
                ('type_2', models.CharField(blank=True, max_length=500, null=True)),
                ('price_2', models.IntegerField(blank=True, null=True)),
                ('type_3', models.CharField(blank=True, max_length=500, null=True)),
                ('price_3', models.IntegerField(blank=True, null=True)),
                ('type_4', models.CharField(blank=True, max_length=500, null=True)),
                ('price_4', models.IntegerField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ershbot_api.Section')),
            ],
        ),
    ]
